---
- name: Log cleanup script for wso2 log-files
  hosts: wso2_nonprod
  remote_user: wso2
  vars:
    source_dir: /opt/wso2/wso2mi-4.1.0/repository/logs
    #source_dir: /opt/wso2/test_log_dir/logs
  tasks:
    - name: Find log files older than 30 days
      ansible.builtin.find:
        paths: "{{ source_dir }}"
        patterns: "*.log"
        age: 30d
        recurse: yes
      register: old_logs

    - name: Display log files obtained
      ansible.builtin.debug:
        msg: "{{ old_logs.files | map(attribute='path') | list }}"

    - name: Removing log files older than 30 days ...
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_logs.files }}"

    - name: Gather date and time facts
      ansible.builtin.setup:
        filter: ansible_date_time

    - name: Generate HTML report from template
      ansible.builtin.template:
        src: log-report.html.j2
        dest: /opt/wso2/email_reports/log_cleanup_report.html
        #dest: /opt/wso2/test_email_reports/log_cleanup_report.html

    - name: Read HTML report from remote host
      ansible.builtin.slurp:
        src: /opt/wso2/email_reports/log_cleanup_report.html
        #src: /opt/wso2/test_email_reports/log_cleanup_report.html
      register: html_report

    - name: Send HTML email report from remote host
      community.general.mail:
        host: "mail.fnb.co.za"
        port: 25
        to: "tienie.vanrooyen@fnb.co.za ,Nico.Modiba@fnb.co.za"
        from: "CRO-IT-DevOps@fnb.co.za"
        subject: "Log Cleanup Report for Server {{ ansible_fqdn }}"
        subtype: html
        body: "{{ html_report.content | b64decode }}"
      delegate_to: localhost
